#!/usr/bin/env python3
from __future__ import annotations

import argparse
import os
import tomllib
from pathlib import Path
from typing import Any

FAIR_SPLITS = {"train", "public_test"}


def _quote(value: str) -> str:
    escaped = value.replace("\\", "\\\\").replace('"', '\\"')
    return f'"{escaped}"'


def _resolve_map_path(path: str | None) -> Path:
    if path:
        return Path(path).expanduser().resolve()
    return (
        Path(__file__).resolve().parents[1]
        / "configs"
        / "rl"
        / "mera"
        / "task_map.toml"
    )


def _load_task_map(path: Path) -> dict[str, Any]:
    if not path.exists():
        raise FileNotFoundError(f"Task map not found: {path}")
    with path.open("rb") as handle:
        data = tomllib.load(handle)
    if "task" not in data or not isinstance(data["task"], dict):
        raise ValueError(f"Task map has no [task.*] entries: {path}")
    return data


def _parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Render a hosted Prime RL config for a MERA task."
    )
    parser.add_argument("--task", required=True, help="MERA task id (e.g. mathlogicqa)")
    parser.add_argument(
        "--owner",
        default=os.getenv("PRIME_ENV_OWNER"),
        help="Environment owner slug (or set PRIME_ENV_OWNER).",
    )
    parser.add_argument(
        "--output",
        required=True,
        type=Path,
        help="Output TOML path.",
    )
    parser.add_argument(
        "--task-map",
        default=None,
        help="Optional path to task_map.toml.",
    )
    parser.add_argument("--model", default=None, help="Override model.")
    parser.add_argument("--max-steps", type=int, default=None, help="Override max_steps.")
    parser.add_argument("--batch-size", type=int, default=None, help="Override batch_size.")
    parser.add_argument("--learning-rate", type=float, default=None, help="Override learning rate.")
    parser.add_argument("--lora-alpha", type=int, default=None, help="Enable hosted RL LoRA with this alpha.")
    parser.add_argument(
        "--rollouts-per-example",
        type=int,
        default=None,
        help="Override rollouts_per_example.",
    )
    parser.add_argument(
        "--max-tokens",
        type=int,
        default=None,
        help="Override sampling.max_tokens.",
    )
    parser.add_argument(
        "--allow-nonfair",
        action="store_true",
        help="Allow task splits outside train/public_test.",
    )
    parser.add_argument(
        "--checkpoint-id",
        default=None,
        help="Optional warm-start checkpoint id.",
    )
    parser.add_argument(
        "--checkpoint-interval",
        type=int,
        default=None,
        help="Optional checkpoint save interval.",
    )
    parser.add_argument(
        "--checkpoint-keep-cloud",
        type=int,
        default=None,
        help="Optional number of checkpoints to retain in cloud storage.",
    )
    parser.add_argument(
        "--eval-interval",
        type=int,
        default=None,
        help="Optional hosted online eval interval.",
    )
    parser.add_argument(
        "--eval-num-examples",
        type=int,
        default=None,
        help="Optional hosted online eval example count.",
    )
    parser.add_argument(
        "--eval-rollouts-per-example",
        type=int,
        default=None,
        help="Optional hosted online eval rollouts per example.",
    )
    parser.add_argument(
        "--eval-base-model",
        action="store_true",
        help="If set, evaluate the base model alongside the RL policy during hosted training.",
    )
    parser.add_argument("--run-name", default=None, help="Optional run name.")
    parser.add_argument("--wandb-project", default=None, help="Optional W&B project.")
    parser.add_argument("--wandb-entity", default=None, help="Optional W&B entity.")
    parser.add_argument("--wandb-name", default=None, help="Optional W&B run name.")
    return parser.parse_args()


def _build_config_text(
    *,
    task: str,
    owner: str,
    split: str,
    model: str,
    max_steps: int,
    batch_size: int,
    learning_rate: float | None,
    lora_alpha: int | None,
    rollouts_per_example: int,
    max_tokens: int,
    checkpoint_id: str | None,
    checkpoint_interval: int | None,
    checkpoint_keep_cloud: int | None,
    eval_interval: int | None,
    eval_num_examples: int | None,
    eval_rollouts_per_example: int | None,
    eval_base_model: bool,
    run_name: str | None,
    wandb_project: str | None,
    wandb_entity: str | None,
    wandb_name: str | None,
) -> str:
    lines = [
        "# Generated by scripts/render_hosted_config.py",
        f'name = {_quote(run_name)}' if run_name else "",
        f"model = {_quote(model)}",
        f"max_steps = {max_steps}",
        f"batch_size = {batch_size}",
        f"rollouts_per_example = {rollouts_per_example}",
    ]

    if checkpoint_id:
        lines.append(f"checkpoint_id = {_quote(checkpoint_id)}")
    if learning_rate is not None:
        lines.append(f"learning_rate = {learning_rate}")
    if lora_alpha is not None:
        lines.append(f"lora_alpha = {lora_alpha}")

    lines.extend(
        [
            "",
            "[sampling]",
            f"max_tokens = {max_tokens}",
            "",
            "[[env]]",
            f"id = {_quote(f'{owner}/{task}')}",
            f'args = {{ split = "{split}" }}',
        ]
    )

    if checkpoint_interval is not None or checkpoint_keep_cloud is not None:
        lines.extend(["", "[checkpoints]"])
        if checkpoint_interval is not None:
            lines.append(f"interval = {checkpoint_interval}")
        if checkpoint_keep_cloud is not None:
            lines.append(f"keep_cloud = {checkpoint_keep_cloud}")

    if eval_interval is not None:
        lines.extend(["", "[eval]", f"interval = {eval_interval}"])
        if eval_num_examples is not None:
            lines.append(f"num_examples = {eval_num_examples}")
        if eval_rollouts_per_example is not None:
            lines.append(f"rollouts_per_example = {eval_rollouts_per_example}")
        if eval_base_model:
            lines.append("eval_base_model = true")
        lines.extend(
            [
                "",
                "[[eval.env]]",
                f"id = {_quote(f'{owner}/{task}')}",
                f'args = {{ split = "{split}" }}',
            ]
        )

    if any([wandb_project, wandb_entity, wandb_name]):
        lines.extend(["", "[wandb]"])
        if wandb_project:
            lines.append(f"project = {_quote(wandb_project)}")
        if wandb_entity:
            lines.append(f"entity = {_quote(wandb_entity)}")
        if wandb_name:
            lines.append(f"name = {_quote(wandb_name)}")

    filtered = [line for line in lines if line != ""]
    return "\n".join(filtered) + "\n"


def main() -> None:
    args = _parse_args()

    if not args.owner:
        raise ValueError("Owner slug is required. Pass --owner or set PRIME_ENV_OWNER.")
    owner = args.owner.strip().strip("/")
    if not owner:
        raise ValueError("Owner slug cannot be empty.")

    task_map_path = _resolve_map_path(args.task_map)
    task_map = _load_task_map(task_map_path)
    task_cfg = task_map["task"].get(args.task)
    if not isinstance(task_cfg, dict):
        known = ", ".join(sorted(task_map["task"].keys()))
        raise ValueError(f"Unknown task '{args.task}'. Known tasks: {known}")

    split = str(task_cfg.get("split", "train"))
    if split not in FAIR_SPLITS and not args.allow_nonfair:
        raise ValueError(
            f"Task '{args.task}' uses split '{split}' (non-fair). "
            "Pass --allow-nonfair to proceed."
        )

    model = args.model or str(task_map.get("default_model", "Qwen/Qwen3-4B-Instruct-2507"))
    max_steps = int(args.max_steps or task_map.get("default_max_steps", 400))
    batch_size = int(args.batch_size or task_map.get("default_batch_size", 32))
    learning_rate = (
        float(args.learning_rate)
        if args.learning_rate is not None
        else (
            float(task_cfg.get("learning_rate"))
            if task_cfg.get("learning_rate") is not None
            else (
                float(task_map.get("default_learning_rate"))
                if task_map.get("default_learning_rate") is not None
                else None
            )
        )
    )
    lora_alpha = (
        int(args.lora_alpha)
        if args.lora_alpha is not None
        else (
            int(task_cfg.get("lora_alpha"))
            if task_cfg.get("lora_alpha") is not None
            else (
                int(task_map.get("default_lora_alpha"))
                if task_map.get("default_lora_alpha") is not None
                else None
            )
        )
    )
    rollouts_per_example = int(
        args.rollouts_per_example or task_map.get("default_rollouts_per_example", 8)
    )
    max_tokens = int(
        args.max_tokens or task_cfg.get("max_tokens") or task_map.get("default_max_tokens", 192)
    )
    checkpoint_interval = (
        int(args.checkpoint_interval)
        if args.checkpoint_interval is not None
        else (
            int(task_cfg.get("checkpoint_interval"))
            if task_cfg.get("checkpoint_interval") is not None
            else (
                int(task_map.get("default_checkpoint_interval"))
                if task_map.get("default_checkpoint_interval") is not None
                else None
            )
        )
    )
    checkpoint_keep_cloud = (
        int(args.checkpoint_keep_cloud)
        if args.checkpoint_keep_cloud is not None
        else (
            int(task_cfg.get("checkpoint_keep_cloud"))
            if task_cfg.get("checkpoint_keep_cloud") is not None
            else (
                int(task_map.get("default_checkpoint_keep_cloud"))
                if task_map.get("default_checkpoint_keep_cloud") is not None
                else None
            )
        )
    )

    config_text = _build_config_text(
        task=args.task,
        owner=owner,
        split=split,
        model=model,
        max_steps=max_steps,
        batch_size=batch_size,
        learning_rate=learning_rate,
        lora_alpha=lora_alpha,
        rollouts_per_example=rollouts_per_example,
        max_tokens=max_tokens,
        checkpoint_id=args.checkpoint_id,
        checkpoint_interval=checkpoint_interval,
        checkpoint_keep_cloud=checkpoint_keep_cloud,
        eval_interval=args.eval_interval,
        eval_num_examples=args.eval_num_examples,
        eval_rollouts_per_example=args.eval_rollouts_per_example,
        eval_base_model=args.eval_base_model,
        run_name=args.run_name,
        wandb_project=args.wandb_project,
        wandb_entity=args.wandb_entity,
        wandb_name=args.wandb_name,
    )

    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(config_text, encoding="utf-8")
    print(args.output)


if __name__ == "__main__":
    main()
